/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class AddSubjects extends javax.swing.JFrame {

    /**
     * Creates new form AddSubjects
     */
    public AddSubjects() {
        initComponents();
        setSize(350, 250);
        setResizable(false);
        setTitle("Agregar Asignatura");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/images/walpaper.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_welcome = new javax.swing.JLabel();
        jLabel_User3 = new javax.swing.JLabel();
        txt_subject = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_welcome.setText("Agregar Asignatura");
        getContentPane().add(jLabel_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel_User3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_User3.setText("Nombre de la Asignatura");
        getContentPane().add(jLabel_User3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txt_subject.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, 25));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String subjects = txt_subject.getText().trim();
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select id from subjects where name = '" + subjects + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Asignatura ya registrada.");
                cn.close();
            } else {

                cn.close();

                try {

                    Connection cn2 = Conexion.conectar();
                    PreparedStatement pst2 = cn2.prepareStatement(
                            "insert into subjects values (?,?)");
                    pst2.setInt(1, 0);
                    pst2.setString(2, subjects);
                    
                    pst2.executeUpdate();
                    cn2.close();

                    JOptionPane.showMessageDialog(null, "Registro Exitoso.");
                    this.dispose();

                } catch (SQLException e) {
                    System.err.println("Error en Registrar la asignatura. " + e);
                    JOptionPane.showMessageDialog(null, "Error! al registrar, contacte al administrador");
                }

            }

        } catch (SQLException e) {
            System.err.println("Error en validar que la asignatura ya esta registrada " + e);
            JOptionPane.showMessageDialog(null, "Error! al validar que la asignatura ya esta registrada, contacate al administrador.");
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSubjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_User3;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_welcome;
    private javax.swing.JTextField txt_subject;
    // End of variables declaration//GEN-END:variables
}
