package ventanas;

import clases.Conexion;
import clases.cripto;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class AddUser extends javax.swing.JFrame {
    
    String title;

    public AddUser(String title) {
        initComponents();
        
        this.title = title;
        
        setSize(600, 500);
        setResizable(false);
        setTitle("Agregar " + this.title);
        setLocationRelativeTo(null);
        
        jLabel_welcome.setText("Agregar " + this.title);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/walpaper.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_welcome = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel_User3 = new javax.swing.JLabel();
        jLabel_User4 = new javax.swing.JLabel();
        txt_lastnamef = new javax.swing.JTextField();
        jLabel_User5 = new javax.swing.JLabel();
        txt_lastnamem = new javax.swing.JTextField();
        jLabel_User6 = new javax.swing.JLabel();
        jLabel_User7 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        jLabel_User8 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        cmb_gender = new javax.swing.JComboBox<>();
        jLabel_User9 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel_User10 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_welcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_welcome.setText("Agregar Administrador");
        getContentPane().add(jLabel_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, 30));

        jLabel_User3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User3.setText("Genero");
        getContentPane().add(jLabel_User3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel_User4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User4.setText("Nombre:");
        getContentPane().add(jLabel_User4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txt_lastnamef.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_lastnamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 30));

        jLabel_User5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User5.setText("Apellido Paterno");
        getContentPane().add(jLabel_User5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txt_lastnamem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_lastnamem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 250, 30));

        jLabel_User6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User6.setText("Apellido Materno");
        getContentPane().add(jLabel_User6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel_User7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User7.setText("Edad");
        getContentPane().add(jLabel_User7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txt_age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 250, 30));

        jLabel_User8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User8.setText("Celular");
        getContentPane().add(jLabel_User8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        txt_phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 250, 30));

        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino", "Otro" }));
        getContentPane().add(cmb_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 110, 30));

        jLabel_User9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User9.setText("Usuario");
        getContentPane().add(jLabel_User9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        txt_user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 250, 30));

        jLabel_User10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User10.setText("Contraseña");
        getContentPane().add(jLabel_User10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txt_pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 100, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int gender_cmb, validacion = 0;
        String name, lastnamef, lastnamem, age, phone, username, pass, pass_encritada, gender_string = "";

        name = txt_name.getText().trim();
        lastnamef = txt_lastnamef.getText().trim();
        lastnamem = txt_lastnamem.getText().trim();
        age = txt_age.getText().trim();
        phone = txt_phone.getText().trim();
        username = txt_user.getText().trim();
        pass = txt_pass.getText().trim();
        gender_cmb = cmb_gender.getSelectedIndex() + 1;
        
        if (name.equals("")) {
            txt_name.setBackground(Color.red);
            validacion++;
        }
        if (lastnamef.equals("")) {
            txt_lastnamef.setBackground(Color.red);
            validacion++;
        }
        if (lastnamem.equals("")) {
            txt_lastnamem.setBackground(Color.red);
            validacion++;
        }
        if (age.equals("")) {
            txt_age.setBackground(Color.red);
            validacion++;
        }
        if (phone.equals("")) {
            txt_phone.setBackground(Color.red);
            validacion++;
        }
        if (username.equals("")) {
            txt_user.setBackground(Color.red);
            validacion++;
        }
        if (pass.equals("")) {
            txt_pass.setBackground(Color.red);
            validacion++;
        }
        
        switch (gender_cmb) {
            case 1:
                gender_string = "Femenino";
                break;
            case 2:
                gender_string = "Masculino";
                break;
            case 3:
                gender_string = "Otro";
                break;
            default:
                break;
        }
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select user from users where user = '" + username + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                txt_user.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                cn.close();
            } else {
                
                cn.close();
                
                if (validacion == 0) {
                    
                    cripto cripto = new cripto();
                    pass_encritada = cripto.Encriptar(pass);
                    
                    try {
                        
                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst2 = cn2.prepareStatement(
                            "insert into users values (?,?,?,?,?,?,?,?,?,?)");
                        pst2.setInt(1, 0);
                        pst2.setString(2, name);
                        pst2.setString(3, lastnamef);
                        pst2.setString(4, lastnamem);
                        pst2.setString(5, gender_string);
                        pst2.setString(6, age);
                        pst2.setString(7, username);
                        pst2.setString(8, pass_encritada);
                        if (title.equals("Administrador")){
                            pst2.setString(9, "Administrador");
                        } else {
                            pst2.setString(9, "Estudiante");
                        }
                        
                        pst2.setString(10, phone);
                        
                        pst2.executeUpdate();
                        cn2.close();
                        
                        Clean();
                        
                        txt_name.setBackground(Color.GREEN);
                        txt_lastnamef.setBackground(Color.GREEN);
                        txt_lastnamem.setBackground(Color.GREEN);
                        txt_age.setBackground(Color.GREEN);
                        txt_phone.setBackground(Color.GREEN);
                        txt_user.setBackground(Color.GREEN);
                        txt_pass.setBackground(Color.GREEN);
                        cmb_gender.setBackground(Color.GREEN);
                        
                        JOptionPane.showMessageDialog(null, "Registro Exitoso.");
                        this.dispose();
                        
                    } catch (SQLException e) {
                        System.err.println("Error en Registrar usuario. " + e);
                        JOptionPane.showMessageDialog(null, "Error! al registrar, contacte al administrador");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
                }
                
            }
            
        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usuario " + e);
            JOptionPane.showMessageDialog(null, "Error! al comparar usuario, contacate al administrador.");                    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_User10;
    private javax.swing.JLabel jLabel_User3;
    private javax.swing.JLabel jLabel_User4;
    private javax.swing.JLabel jLabel_User5;
    private javax.swing.JLabel jLabel_User6;
    private javax.swing.JLabel jLabel_User7;
    private javax.swing.JLabel jLabel_User8;
    private javax.swing.JLabel jLabel_User9;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_welcome;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_lastnamef;
    private javax.swing.JTextField txt_lastnamem;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

    public void Clean(){
        txt_name.setText("");
        txt_lastnamef.setText("");
        txt_lastnamem.setText("");
        txt_age.setText("");
        txt_phone.setText("");
        txt_user.setText("");
        txt_pass.setText("");
        cmb_gender.setSelectedIndex(0);
    }
}
