package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author jesus
 */
public class InscriptionStudent extends javax.swing.JFrame {

    int id, cmb_subject;
    String name, lastnamef, lastnamem;

    public InscriptionStudent(int id, String name, String lastnamef, String lastnamem) {
        initComponents();

        this.id = id;
        this.name = name;
        this.lastnamef = lastnamef;
        this.lastnamem = lastnamem;

        setSize(400, 300);
        setResizable(false);
        setTitle("Control de Estudiantes");
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        if (Login.typeUser.equals("Estudiante")) {
            jLabel_welcome.setText("Inscribir");
        } else {
            jLabel_welcome.setText("Inscribir a " + this.name + " " + this.lastnamef + " " + this.lastnamem);
        }

               ImageIcon wallpaper = new ImageIcon("src/images/walpaper.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        cmb_addSubjects();
    }

    private void cmb_addSubjects() {

        int i = 0;

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select name from subjects");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                cmb_subjects.addItem(rs.getString(i + 1));
            }
        } catch (SQLException e) {
            System.err.println("Error! al llenar el combobox de asignaturas." + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_welcome = new javax.swing.JLabel();
        jLabel_User3 = new javax.swing.JLabel();
        cmb_subjects = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_welcome.setText("Inscribir a");
        getContentPane().add(jLabel_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel_User3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_User3.setText("Seleccionar Asignatura");
        getContentPane().add(jLabel_User3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        getContentPane().add(cmb_subjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 220, 35));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Inscribir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 100, 35));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int cmb_subject = this.cmb_subjects.getSelectedIndex() + 1;

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select id from inscriptions where subject = '" + cmb_subject + "' and user = '" + this.id + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Estudiante ya inscrito en la asignatura.");
                cn.close();
            } else {

                cn.close();

                try {

                    Connection cn2 = Conexion.conectar();
                    PreparedStatement pst2 = cn2.prepareStatement(
                            "insert into inscriptions values (?,?,?)");
                    pst2.setInt(1, 0);
                    pst2.setInt(2, id);
                    pst2.setInt(3, cmb_subject);
                    
                    pst2.executeUpdate();
                    cn2.close();

                    JOptionPane.showMessageDialog(null, "Registro Exitoso.");
                    this.dispose();

                } catch (SQLException e) {
                    System.err.println("Error en Registrar isncripción. " + e);
                    JOptionPane.showMessageDialog(null, "Error! al registrar, contacte al administrador");
                }

            }

        } catch (SQLException e) {
            System.err.println("Error en validar que ya esta incrito " + e);
            JOptionPane.showMessageDialog(null, "Error! validar que ya esta inscrito, contacate al administrador.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscriptionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscriptionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscriptionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscriptionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscriptionStudent(0, "", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_subjects;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_User3;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_welcome;
    // End of variables declaration//GEN-END:variables
}
