package ventanas;

import clases.Conexion;
import clases.cripto;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    
    public static String user, typeUser;
    public static int id;
    private String pass;
    
    
    public Login() {
        initComponents();
        setSize(400, 550);
        setResizable(false);
        setTitle("Acceso al sistema");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/images/walpaper.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        ImageIcon wallpaper_logo = new ImageIcon("src/images/itaoLogo.jpg");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(jLabel_Logo.getWidth(),
                jLabel_Logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Logo.setIcon(icono_logo);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbutton_acceder = new javax.swing.JButton();
        jLabel_Footer = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txt_pass = new javax.swing.JPasswordField();
        txt_user = new javax.swing.JTextField();
        jLabel_Pass = new javax.swing.JLabel();
        jLabel_User = new javax.swing.JLabel();
        jLabel_Logo = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbutton_acceder.setBackground(new java.awt.Color(3, 61, 169));
        jbutton_acceder.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbutton_acceder.setText("Iniciar Sesión");
        jbutton_acceder.setBorder(null);
        jbutton_acceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_accederActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 240, 50));

        jLabel_Footer.setText("Creado por Jesús Reyes Hernández ®");
        getContentPane().add(jLabel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 290, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 290, 10));

        txt_pass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_pass.setBorder(null);
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, 30));

        txt_user.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_user.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_user.setBorder(null);
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 290, 30));

        jLabel_Pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Pass.setText("Contraseña");
        getContentPane().add(jLabel_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel_User.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_User.setText("Usuario");
        getContentPane().add(jLabel_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        getContentPane().add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 250, 250));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_accederActionPerformed

        user = txt_user.getText().trim();
        pass = txt_pass.getText().trim();
        
        if (!user.equals("") && !pass.equals("")) {
            
            try {
                
                cripto cripto = new cripto();
                String pass_encritada = cripto.Encriptar(pass);
                
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select id, typeofuser from users where user = '" + user
                        + "' and password = '" + pass_encritada + "'");

                ResultSet rs = pst.executeQuery();
                if (rs.next()) {

                    id = rs.getInt("id");
                    typeUser = rs.getString("typeofuser");  
                    
                    if (typeUser.equals("Superusuario")) {
                        
                        dispose();//JFrame destruido y limpiado por el sistema operativo
                        new Superuser().setVisible(true);
                        
                    } else if (typeUser.equals("Administrador")) {
                        
                        dispose();//JFrame destruido y limpiado por el sistema operativo
                        new Admin().setVisible(true);
                        
                    } else if (typeUser.equals("Estudiante")) {
                        
                        dispose();
                        new Student().setVisible(true);
           
                    } 
                    
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos.");
                    txt_user.setText("");
                    txt_pass.setText("");
                    
                }

            } catch (SQLException e) {
                System.err.print("Error en el botón Acceder." + e);
                JOptionPane.showMessageDialog(null, "Error al iniciar sesión!, contacte al administrador");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        }       
    }//GEN-LAST:event_jbutton_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Pass;
    private javax.swing.JLabel jLabel_User;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbutton_acceder;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
